# Generated by Django 4.2.2 on 2023-06-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_namedb_delete_messagedb_delete_roomdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedb',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
